on: [push, pull_request]
name: R-CMD-check-relative

jobs:
  R-CMD-check-relative:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: windows-latest, r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'devel'}
          - {os: macOS-latest, r: 'oldrel'}
          - {os: macOS-latest, r: 'release'}
          - {os: macOS-latest, r: 'devel'}
          - {os: ubuntu-20.04, r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          #r-version: ${{ matrix.config.r }}
          # http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-r-dependencies
        with:
          cache-version: 3
          extra-packages: any::rcmdcheck, local::.
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
